//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSCC.Fees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeFee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollegeFee()
        {
            this.Programs = new HashSet<Program>();
        }
    
        public int CollegeFeeID { get; set; }
        public int AcademicYearID { get; set; }
        public string Name { get; set; }
        public int AmountDomestic { get; set; }
        public int AmountInternational { get; set; }
        public bool IncludeOnCreateProgram { get; set; }
        public string LookupName { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs { get; set; }
    }
}
