//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSCC.Fees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostItem
    {
        public int CostItemID { get; set; }
        public int ProgramID { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
    
        public virtual Program Program { get; set; }
    }
}
