//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSCC.Fees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.CostItems = new HashSet<CostItem>();
            this.Schedules = new HashSet<Schedule>();
            this.CollegeFees = new HashSet<CollegeFee>();
        }
    
        public int ProgramID { get; set; }
        public int AcademicYearID { get; set; }
        public int SchoolID { get; set; }
        public int TuitionID { get; set; }
        public string Name { get; set; }
        public string ProgramPageLink { get; set; }
        public string AcadProg { get; set; }
        public string AcadPlan { get; set; }
        public Nullable<bool> IsInternationalOffering { get; set; }
        public Nullable<bool> IsPartTime { get; set; }
        public Nullable<int> NonStandardTuition { get; set; }
        public Nullable<int> FirstTermPayment { get; set; }
        public int CoopTypeID { get; set; }
        public Nullable<int> AmountCoopDomestic { get; set; }
        public Nullable<int> AmountCoopInternational { get; set; }
        public Nullable<int> AmountTextBooks { get; set; }
        public Nullable<int> AmountSupplies { get; set; }
        public bool IsPublished { get; set; }
        public string NotesInternal { get; set; }
        public string NotesTuitionCollegeFees { get; set; }
        public string NotesTextBooks { get; set; }
        public string NotesProgramCosts { get; set; }
        public string NotesSchedule { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedByFirstname { get; set; }
        public string LastModifiedByLastname { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostItem> CostItems { get; set; }
        public virtual School School { get; set; }
        public virtual Tuition Tuition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeFee> CollegeFees { get; set; }
    }
}
